import sys

def parse_fasta(fasta_data):
    """
    Parses raw FASTA string data into a list of DNA sequences.
    
    Logic: 
    FASTA files start with '>' followed by a label. The sequence follows 
    on the next lines. We need to join multi-line sequences into one string.
    """
    sequences = []
    current_seq = []
    
    # Split the raw data by lines
    lines = fasta_data.strip().split('\n')
    
    for line in lines:
        line = line.strip()
        if not line: continue # Skip empty lines
        
        if line.startswith('>'):
            # If we have a current sequence built up, save it before starting a new one
            if current_seq:
                sequences.append("".join(current_seq))
                current_seq = []
        else:
            # Just add the DNA chunk to the current sequence buffer
            current_seq.append(line)
            
    # Don't forget to add the very last sequence!
    if current_seq:
        sequences.append("".join(current_seq))
        
    return sequences

def solve_consensus(fasta_data):
    # 1. Get the list of strings using our tool
    dna_strings = parse_fasta(fasta_data)
    
    # 2. Transpose the data using zip(*dna_strings)
    # This turns rows of DNA into columns of nucleotides.
    # Example: [('A', 'G', 'T'), ('C', 'C', 'A')...]
    columns = list(zip(*dna_strings))
    
    profile_matrix = {
        'A': [],
        'C': [],
        'G': [],
        'T': []
    }
    
    consensus_string = []
    
    # 3. Analyze each column
    for col in columns:
        # Count occurrences in this specific vertical column
        a_count = col.count('A')
        c_count = col.count('C')
        g_count = col.count('G')
        t_count = col.count('T')
        
        # Append counts to our profile matrix
        profile_matrix['A'].append(a_count)
        profile_matrix['C'].append(c_count)
        profile_matrix['G'].append(g_count)
        profile_matrix['T'].append(t_count)
        
        # 4. Determine Consensus
        # We create a temporary dict for this column to find the max
        current_counts = {'A': a_count, 'C': c_count, 'G': g_count, 'T': t_count}
        # max() finds the key with the highest value
        # We assume if there's a tie, any winner is fine (Rosalind accepts any).
        winner = max(current_counts, key=current_counts.get)
        consensus_string.append(winner)
        
    # --- OUTPUT ---
    
    # Print Consensus String
    print("".join(consensus_string))
    
    # Print Profile Matrix in the specific format required (A: 1 2 3...)
    for base in ['A', 'C', 'G', 'T']:
        # Convert list of integers to a string separated by spaces
        # map(str, list) converts [1, 2] -> ['1', '2']
        counts_str = " ".join(map(str, profile_matrix[base]))
        print(f"{base}: {counts_str}")

# --- Sample Execution ---
# You can paste the "Sample Dataset" from the screenshot here to test.
sample_input = """
>Rosalind_5356
CGGGCCTCTGGTCTTCCCATAACACAAGAGATGTACGTTGGGAGAGTGCGTAATTCACCG
CGAGTTAGCCGACGCGACTAGCCCGATAGGGTGGTTGTACAAACTGTGGAGTACGCAGAA
GTCGCTGGACTCTAGACCTGCCTGTAGGGGTTGACGAAATCGAAGTGGCACTCTTGACAA
GAGCGCATTTGCTTGTTGAAAACCCCCGAACGCACAACATGATCCGCTATGGAATCACCA
CTTCCAACTGCGTGCTAGAATGCCAGTCGCGGCCTGTTCTCTCCGCGACCCAACAGTGTG
CATTAGCGTCACGGCCTTGCAGCTGGTAGTTCTTAACTAGGTGTGTACGTGTGTGCGTTA
TGCCATCGGAAGCAATGTCCCCCACGTCCCTAAGGCTACATCGGAACAGGTCAGTACATA
AGGGGTATCGGACGGGTGTAAAGCCCCCTGACTCCGTCGCGTGTGCCCTATCTCTGATAC
AAGTTAGGAAAAATATCCTTAAAATTGGGACTACTCCGTTAGGTAAAGGATGGAGGCGCC
ACGGCTCCACGATTAGGGTTAGTTTCACATGAGCCGTGGAATGGTAATCCAGTTCTAAAT
CTGGATGATCGGCGTGGACTTGTTGTCTGCTCATGGGGGATCAATTGGTACCATTTTGGC
ACACGAGTCGGGCGTCCCGCACCGTGCTAACGCCCAGACAATATACGAATCGCAATGAGA
TGGTCCTAACTGATGGATAATTGGTAAGTTCTGGCCCCGAGTGTTGTGGAATCCACCTGA
AGCCAGATGCACGAACCACGCGCCACCTCAACCAGTGGCAATAACCGGGGGTGGTTCGGA
AAGTGTCCCTATAACAACCGTGAAGTGCGCGCGAGGTCCGTTTTCACCGGGTGAACTACG
CATATATGAATTGGGTCATA
>Rosalind_3639
AGCAATCAGCCTCTTATCGTCGTTGATCGTATATCACGGTAAATCAGATTCACCTATAAA
CTCGGTGAGTCTATGTGATTTAGTTCCGAGGGCTCATCCTTCGCGGACCATCTAGCCAAT
ATTTCGTCTTCCCGTAACATCAAGTTCAGCTGTAATGAGGTAGCTGCAGGTCGTGTTGAG
GGGTCTGCTCTGGAGCGAAGTCCTCGTCACCCCTTGTACAATTTAGTGCCACGTTGGGCC
TTATGCAGAACCGATTATAAGCACGCTTCCATTTTGCTAACGAAACACGGAAGTTACGGG
TACTCGCGACTCGTGCTGGCATCTTGGAATGCGATTCGGTTCCCATACCTGCCAAGGAGT
GTCTATATCTGTCAGGGTACAAGCTGCGAATGCTCGCCTGTCCCGGTCTCAGATGCTGTG
ACAGATCACACCTTCAGGGTGGAACTCTTGTCGTGCCAATTCTTACCATCCTGTGACAAT
CGAACCATTTAAGAATACCCTGGCCCGAATTGGAACAGGGGACTTGGCTTGGCTTTGTAA
AACTTTATTCCTGTTGTAGCATCTCCGCCTATGGGCTTAGTGCCCAGACAGTGTTACTTT
GGTTACCAAAACTGAGGTCTTTAGGGATTGGCGCAGCGTCGAACTTTTCGCGGTAGCCAC
TCGCGGGTTACTATTTCTACGAAATTCGAGTTCTCGAGTTAACGGTCTGCTCGTCGCGGT
GGTTGTTGCCGTCAGAGTCCCGTGGCCTCACTCGTGCCCCCTGCGCCCACGCCGCCAGGG
TCTACGACACAAAGTGCTACTAGACCATACCAAGCGCCGACCTTAATATTGGTAGCAGCT
CTAATGGCCATTCGTTATGTAGTCCGTTGAGTCACACCGTTGCCGCAAAACTCAAAGTTG
GTGTTGCGGGGTAACTCGAT
>Rosalind_5295
CATCCAGAACCCTCCGTAGAATGAATGGACGAGCCGTCCAGCCCTGTGTCCTGTGAAAAA
TAGTTAGTTGTTCGCTCTAGCGTAGGTACTCTCTGATGCATAGTTCTGCATTGGCCCCTC
TATGATCTCGGCCACTCGCCTTCGGGTCCTCTGGAACCCTCTAGCAATGTAAGATTCGTC
ATGTTAACACAAAAGAGTTTTGCTGTTTTATGTCGTCGGATACGTTTCAACATCTCGGGC
GGTTCTTTGCGTCTTTCAGAGGTTTAGGGTATTGTACCAACAGAGAATTCGCCTCATTCA
TGTCAGTCTACCAGTCTAGTGCTATGGGAGACATTGGCGGCGACATGATGGATATGTTGA
GTTTGTAGAAACTGACTTTGTAAGCGTAGGTGGGCGTGCACACGTCCCCGACCCGCTGAG
CAGCCTGTACTGAGGCAAACTCACCCCTGTCCAAATTCTACCAATTAAGAACATCATGTG
TGTCATATCTCCCGGTTGTCCACTTGTGTAAAGGGGCCGATAGAGGAGCAACGGGATATA
GCAAATAAGTATGATTCATGCTTATAGCTATGCCACAGTTTTTTCTAAATGTGCGAATCA
GACAGGCCAAGGTGTGACACCGGAAGTTCAGACGATTCCCATGTGATGGTTAAGGCGAAT
TGATAACGTAACTTGAGCTAGTTATAATGAATTTGATGATGATGAGAGGCCTATCTGTAT
TTGCAACCACGTGATACTGGAATCGAACATCGTAGATACACTGTCAGGGATTTTGTGTAC
TCCTAGGTCTTCCCTCGATAGCCGTGACGCAGGGGACGCTTTCAACTCATGCAGCTGTAA
GATGGGGCAGTGGGGTATCTATTTCTAGTTGAGAAATTCTTCCCTTGGGTAGCGACGTGA
CGTCTCGGCGACTCTCCGGG
>Rosalind_1697
CCGCGTTTCCAACGAAGAACAGTCCAGTCCCGAAGGGTGTCGGGTGGATCTACCTGAGAC
GTCCGCGTTCTCAAGCTGGGTTACAATTCGTAAGCACGCTGAGCGGTCCGGCGAATAAAG
GTCTGAATCGAGTTTAACGGGTTACATGTGTTATAGAAATCACCCATGTTCCAACACAAA
GTGGATATAGTAGTCTGCCGAATCAGGTCGTTATCAAGACAGCCGGTTCTGTTCTAATGC
CATTTTTGGCGGGACCGGCTATTGTATAGGATGCCCACATTCATAACGCAAGAGATTTGT
CTCTGTGTGCTCATCTGTATCAGAGGCACGACCCCTTTTAAGTCACCTTCGTGGATTGAG
CACACGGATAGTCCGGCATACGCCTCCAACTTTGAATTACCAACCAACTTTATCGTAGAT
CCCTAACCGGGCATTAAGGTCATTTCGGATAGGACTCTCGACGTAACTCCGAACATCTGA
AATGGAACTTCGCTGCATAATCCTCATTTTACGGCCTGGATCGAGTAATCGTCAGGACCC
AAATTAACTACTGGACCTTTCCGATCGCAAGCGGTAAAGTGCCCGGCAGAGTGCAGTACA
ACGAACGTGTTTAGTCCGGAAGTAGGTCGGGGATATGCACTAGCTCAGTAGCAAGTGCGG
ACGAGCCTTGCGATGCTTACGGAAACATCGAACAGCGGGGATGAACTTTAGACGTACCGG
GAACTCGAGCTACTCGAAGCTACAGATCGTTTTATGTTTGAATGGTTAGTCGACTCCCTT
GTTACATGCGATAGCTCACTCTCTGCCGAACTTTAGTTATAGGAAGGGCCAGAGTTCAAA
GTAGATTAATACTAGGATAATGTTATGGCCGGGTGCTCTGCCAGGGATATGCTAGGGCTA
CTATAAGGTAGTCCTAAGTA
>Rosalind_6001
TGACATTGGTTAGCCATGGTAGCAACTACTCATTTCCATCGCAGGGATCGCGAAGACCAT
AAGGAGAAATTTACGGAAACATCACGAGGTGACCAAGCCTCTGTCTAGGTTATCTACCAG
CATCCAAAACTCCGTCGCGGACCGGCCGACAAGTCGACCGCGAGATCTTTCGGCCTGAGC
CTGGTGGACCGAACTCACCACGCTGATCACCCTTCTGAACTTGCCTCCGCGCCTGTCGCT
CCCTTTAGGACTCGGCACAGAGACCCCCTTGGTTTTGTGAACTAGTGGATTAAACGATCA
ACCTCATAACAGTCGATTATCACCGCAAAAAGTTAGCAACGCTAAAGGTGATCTCTCAAG
GATGAAAATACAGTTGGTTGGAAAGGACGGATGTTCGTTACCATGTTCGGGGCATTGCCA
CGCTTCTAAGAAGGGAGACAACCCTCTGGACAGTCATGATAATCTGGTTCTAGGTACTCC
CTCCCTCTACCTTCGGAGACTATCATCCGGGTAATCGGACCTGGCAGTTCACATCACTGA
AAGTCAGGTGAGCCCCGCTGTGACCCGTGGTCAATGCTGATTGTATTGATATCTGATCAA
TGTGTTGCATAAATACTTGTGCCTCACGCGCCTCCTGATTGTCATACCCCATAAGAGTAG
TAACCTTCCCAGTACATAGAGCCGGCATTCTCCGACTAGCACATCGGATAGCTCTGACGG
GGTGCGCGGTAGAGGAGCTCTTCCGGGTCCACAAAGCCTCCCTCGCAAACATGGATAGTA
GAGAATTTACCTCTTTAGCATTTTTCGCAATATAGCCAAACATTTAAGACCGACTGCGTC
GACCCGCCGTGAATCGGCGAATCCTTAAAATCGGGGCAGACCTTACCTAAGGTCAGTACA
AATTCATACCCGCCAACTGA
>Rosalind_7744
CTAGGTGTTGTGTCACCTTCATAGACGCCAGAGGCCCGCCCCTCTGGCAACGTGATCTAG
ATTGAATGATAACAGCCCTGACAACAGAGCCTGCGCGGCTCGTAAGATGCGTAAAAGAGT
TTACTCCGCGTGGAAACGCAAGGTGATTTAAACGACGAGCGTTTCTTAAATGGGGTAGGT
AAAGTGTGGCACGGTTCTCAGACGTGAAGTCACAACCGATTACACAGGCAAATCCGAATG
AGACCCTACCGCTATAGTGATTCAGTTCGCCTAAGGAGGTAGACTCACAGCCTCGTTCTT
ATTTTCGTTACTTGTTATACAGTAGGGCAGGGCCAGCCGCTAAGATCGTATTTGACATAT
GGGAAACCCCTATTAGGCACTCTCCGGTAGCGTCGACTGCGCAGTTGCGAATTCGTAGGC
ACCATGTCCGTTAGAAGTGTCCTTCGGCAAATGAATTGTTACACCCCTATGCCCCCATCA
GAATTGTTATATTGGGAGCAGCTTCAATCCTGCCTGATGACACGTCAACAATAACACTGC
TTGGGGCTTTATCTCATGTAGTTCAACCTGGATTGTACCCTCATTTCTGAGCATCGATGT
AGAGCAGATTCGTCTTAACCTTCTGGTAGACGCATCAGTATCCCTGGTGGTCTTCGAAAC
GTTTCTAAATAACTTAAAGCTCACTCTGTCGTGTGTGAAGTTCGAGGGGGTAGTATTCAA
GGAGATTCGCAGTCGTAGGACATTTTAAAGTGCTGGCCGACAAGAATGACAAAAGCACTA
TCGCGAGCGGAACCACCTTGACATGCGTAGGAGCTTCTTTCGGTCATTGTGTTGGGGGGA
TAGCGGATATGCATCCTGGGTCATTGTGCAGTGTATCAGTAGCAAGCTTGCATTCGTTTG
AGAGTACCAGGGACTTGGAC
>Rosalind_2230
AGCCTTCCAATCTTGGAGATTAGAACCTACAGGGACGCCTTACCCCTTGGCTCCGGTCTG
CCTGCAAACAGATTAGGGGCGTCAAACCAACGTGAGCTCCGTCTAACATCCAGAAGGCTT
ATTTGCATGCATCGGCGACTTTTGGGACCCAAGCATGTACCCGGTAAACATGTCAGGAGA
AAATCCCTGGGTGGCCGTTCCCGTGGTTTACACCGGTCCTCTCGAAAGTCCCCGGCATTT
CAAGCAATGTGCCCGCCGTATCTGCTGGCTGAGTCATAGTCGCTGAAGCTTAGAACCCCT
AGGGCTCCTAAGTATAGACTAAATAAACAGTTCTTTGGCTACACCTAGTTTTAAGAATCG
AGACGCACCTTGAAACTCGTATCATACTATAACCAATGGTATCAAGCCTTCAACCTTCGC
GGTAGATTGGACCTCTGACTGCGAGAAATAGCCCCTACCTGTTTGACAAGGGAGAGCTTG
GTCGGCTTGAATTTCAACGGTGCATAATGATTCTTTCAAGTATGGTCACCGCCCACGTCT
TTATCTCCGATACATCCGCGGGTTCCTTCCTACAGTAGTATAATGACACTCGGACACGAG
TGAGTAATTACGGTACATTGACCGATGTTGAGCCTCTGATCATTTCGGCGTGCAAACCAG
GGGATGCCAGTCCCAGTCTTGGGGAACACATTATAAACCAGGAAGGAATAACTATGCAGC
GCTATCCGCGCAACGGAAGAACTTTGAATGTGCAGATGTTCTGTGATCTCCGCATCTGAC
TTACTCCATAGATTTGATGACGCGTAGTCGCATACAGTACAGGGAATTAGAGGCTAAATC
CGTGTGCTGCTACTTGAAACCACGCCCTACATTCAGGAGAGATTGTTTACAGCGGTTATA
ACCTCCTGCTATTTCTCCCC
>Rosalind_4177
TACGCCGAAAGGGCCGTGTCCTGGAATTTCGTCGAACGACAGGTTCGTTCTCTACATATG
GCTGCAAATACGTTTGATGAGTCCCTTTCTGGTCGTGAACAGCGAAATACAGTGCATCAA
GCGGTGTGTCACTTTGGACTCTGGGGGGTGTACATAGGTAGCTTTATGTGACACAGCTGT
ACTTCCCTCGGCGTGGCTCACCACACTCTGGCGCTAGCCCCCGAAAACGCTAATTCGGTA
TCCAGTTCCAACGCGCTGGAGCTTACATAGAGCCAATTATTAGGTGCTGCGGATATACAT
TGTGCTTGCGGCACTCCCCTTGGGCTTTTCAAGCAGCGTAACATATGTTCCGGTCTGGCT
TTTGGTTAATCACGTGCCGGCACTTTTAGGGTCGGATCGAAGTACGTCGACTGGGACAAC
CCGAGTGCGTTCCGTGCCCACTAATGGATTACAATTGCCCCTAAGGGGCGAGAATAACAA
TAAGTGACTGTATACCCCAGACGTCTTCTACGCTGCCAAGCAACCTCCTGCGTTAGCCAT
GCAAAATTATATGGATTGGCAGACAGGGCTTGTTCCCCTCTGCGCTATCACGACAATCAC
GTATCTACTCATTTTTAGATGCGGACGCCTATTACCGTAGTCTAATGCGCAATGATACAG
ACACTGAGTCCCCCTCTCACCCCTTTATGGCTGTCCGTTGAGTTACGCGGAGAATTGTAG
TTTAACGATAAGGATGCATCTGATACGAGCTTACCACCTCTTTCTGCACTACAACCTCCC
AACTAGTCTAAACGGACCGGGCGGATAATTATCTTCCGAAAGTCAATGTTTTCCCATGAC
AAGGTCTATGACGTTACGAGTTAAACCGGCGACCACCGAGGCGGACGTAAGTCAGAATTC
GCATTGCAGTAGGGGCATTA
>Rosalind_9121
GGAGGCTGCTCTTACCAATTGAGTACGCTACCCTGCGGAGAGACGTTGCTAGCTTCTGAC
AATGTTAACCAGTCTGATTTATGTTGGCATTCCCGTATTCCGTGAATCCCTCAAAGACAT
AAGCAGGTCAAGCATTGAGGTAGAAACTCCCGCATACTGATATGAATTGATCATTCTTAA
TATCATAGTGCTGGTATTCGTGGGGAATTTCGCTCTAACCCGTATGAAAAACCAAGACAG
GTAAGTTCTAGATTCCCTGGAGGCTCCCAGTGTCGTAGTATACGTAGTTAACGTCGTTGC
CAACACCTTGGTTCCGCTTCTCCCTGAGTGGGATAGCTTACGAAACAACAGCAGTCGTAC
AGGTCGTACAGCTTTCCACTCGATGCATGGTGGGAGCGTTAAGCCCGTAATAGGGTAGGG
CGAAGACGTTGATCATAGGTCAAGAACACCCGTCAATTGACGTTGGACTTATACGCTCCC
GGCTTGGTAGAGAAATCCCCAAGAGATTCCTCACAATAGCAGCGGAGATTAGCAACGAGA
ACGTCGCAGCACCCAGCTTAAGGCTTTTCAGACACAATTGTTCGAAGTGGTACGTCGTGG
TAACGTCGTCTATTTAAGGATATAGACCCTCAACTCCAACCCCTATTGTAACCTAATATA
ATTTTTCTAAGTTAACATTCCGTGAGGGTTGAAGCGATCGATATCCAAAGGTACCACCTC
TAGAGAGGGTGTTTGGTAACCGTTAACCTATCCAGGGCAGCGAACATTTCGTACTCTATG
TCACGCCGTAAGAGGGGATAGTAAAGCCGAGGTGACTCGGTATCGAGGAGACGTAATATC
TGTTAAAAGGGGGAGCCAGTACCACGGTAGTGACTATTAACCTAAAATTCCACTCAGACC
GTTGAATGGCGGTTTCAATA
>Rosalind_5148
AATATAACGCGAGAGGATAAATAGGGCGTCTATATATACATTAACGCCGTACCGTAGGTC
TTAAAGAATCATAATCTACGACCTCACTAAGTGAAAGAAAGACAAAGTATGGACGGACTG
GAGTCCTAGACGTAATCCAGTGAACGCACCAAGTGTTTCATAGCGAAGGCTTGAGTGAAC
TGACCGGCTACCTAACGGTCATATAACAGAAGATTCTCCGGTCATGTCCGCATAGTCCCT
TGGTCGCGCACGAGGACAAATTTCGCTCCGGTAGGGCTATGCGTTAGTCCGGGTACGCTG
CCCATACTAGGCTCGTGAGTATAATCAGTCGCCCGCGGCAAAAATTAGCCATTTGCTGCG
TCAGAGCGATTGGTATGACGTATCGTAACTGCTTCGCCTGCGGGCCTAGCAGAGGTCACA
ATTTCTGCGGACTGTGCGGGTGACCATGTGGAGGTGCACTCATAGCTAGCATTCATACCT
ACGCTGAATCCGTTTGAGGCTGCTGCGTTCGGGTTTCTGACGTAGAGCATAATACAAACA
TGAAAACCTGTTCATGACATCTCCGTTGAAAAGTTTCTCATTCTCACGGCTGAACTTTTT
TAGGTTCGACCGTACTTCAGAAGGAGACCTTACGCCCATGACTTAAATGACCGCAAATCC
TTAATTGAAACGACCATTTTAGGACGCCCCCGGCTATCGTGCCCTGGGAGTCACGATTGT
GTTCAGATAACCTACTAGCCTCTCCGCTTGGCCGGCTCCCACTACAATTGGGGAGCTTCG
TAAGTAAGATAAACGCCTTCTCTGAGGTTGACAACGTATGACTGCGGGCGTTGGATGGAA
CTAGCCACATTTGTACTCATGACTGGACGCGATGACGAATGGCCTCCCAAAGTCGCATCA
TATAATTATCGTATGATGAT

"""

solve_consensus(sample_input)